### PR TITLE
Added dockerfile

### PR DESCRIPTION
**Pull request by mohamedelhabib**
Is there any change to have a docker image for this tool

### CODE REVIEW

**Comment by codekie** [comment]
@mohamedelhabib thanks for your contribution. Sounds like a good idea. I'll try to come up with an implementation that generates this Dockerfile.

**Comment by mohamedelhabib** [comment]
@codekie the goal by adding a Dockerfile is to be able to build a public docker image.
This can be done by connecting this repo with a docker account, and docker hub will build an image for each commit.
The main condition that the repo have a Dockerfile at top level.

**Comment by codekie** [comment]
Yes, I know. I'm on it 😉

**Comment by mohamedelhabib** [comment]
Ok thanks

**Pull request merged**
