### PR TITLE
feat: do not set noAdditionalProperties on schemas containing JSON schema combiners

### PR DESCRIPTION
**Pull request by DerkSchooltink**
**Problem**

One of the caveats described by this tool is that JSON schema combiners (`oneOf`, `anyOf`, `allOf`, `not`) are not supported when applying the `--no-additional-properties` flag. This flag is incredibly powerful in detecting wrong examples, so not being able to use it when certain schema's in your OpenAPI definition use any of these combiners is a waste of potential.

**Solution**

When applying the `additionalProperties` flag to all schema's, this tool has knowledge of the content of the schema. This knowledge can be used to filter out schema's that contain any of these combiner keywords and simply not apply the `additionalProperties` property to it. 

Additionally, before looping through all paths pointing to places where `additionalProperties` could be applied, you can already filter out the paths that has any of the keywords in its name. For example:

`$['paths']['/path/to/something']['patch']['requestBody']['content']['application/json']['schema']['properties']['path']['items']['allOf'][0]` 

This can be pre-filtered out as `allOf` is in this path. This saves iterations when walking through the JSON and resolving references later on. 

**Appendix**

The fix is a patch for this issue. Ideally this issue would be solved differently but it appears that schema combiner supported is lacking in 3rd party dependencies. Full support for this while checking if the examples are valid would be even better.

If this change is not wanted because it is essentially a patch, let me know and we can start a discussion for a better implementation. :)

### CODE REVIEW

**Comment by codekie** [comment]
You're right with the problem, but not setting the `additionalProperties`-flag does not solve the problem. It just shifts it into the other direction. Meaning, instead of getting false negatives (where properties are allowed), you'll get false positives (where properties are not allowed).

**Comment by DerkSchooltink** [comment]
> You're right with the problem, but not setting the `additionalProperties`-flag does not solve the problem. It just shifts it into the other direction. Meaning, instead of getting false negatives (where properties are allowed), you'll get false positives (where properties are not allowed).

This was the discussion I was hoping for as noted in the appendix, I'm also not quite sure if this is the best solution. 😄 

The main motivation behind this fix is to at least have the benefit of enabling the flag and not failing on the short comings of 3rd party libraries. I'd rather have a false positives than false negatives which I cannot fix (unless if I disable the flag manually). In automated build pipelines a failure is abort the entire build, but a false positive might still be recognised in a peer review. 

Again, if you have any suggestion on how to implement a better fix I'm happy to consider that instead! But as far as I know this is not within reach without considering other 3rd party libs for JSON path references resolving, which has considerable impact I'd assume.

**Comment by codekie** [comment]
I see your point. A viable compromise for me would be, to adapt the caveat in the readme, pointing out that potential errors may be missed if `additionalProperties` and schema combiners are used and additionally log a warning to the console that this combination has been detected.

**Comment by DerkSchooltink** [comment]
> I see your point. A viable compromise for me would be, to adapt the caveat in the readme, pointing out that potential errors may be missed if `additionalProperties` and schema combiners are used and additionally log a warning to the console that this combination has been detected.

That seems like a good addition, I will create a new commit.

**Comment by DerkSchooltink** [comment]
@codekie is there anything else I forgot to add? The new commit should have enriched the documentation and add console warnings if the flag is not applied.

**Comment by codekie** [comment]
@DerkSchooltink No, after a first glance it looks good. But I don't want to merge it in a hassle. Unfortunately I am currently very busy at my job. Once I've got a bit more time, I'll address this. Thanks for your understanding and the efforts you already have put into this 👍

**Comment by codekie** [comment]
@DerkSchooltink I've added a couple of changes. Please let me know if you agree with them.

**Review by DerkSchooltink — COMMENTED** [review]
Looks good to me. I was unaware it only doesn't work with `allOf` :D

**Pull request merged**
